defaults:
  - colors_gs # For more specific color tuning

_target_: tracklab.visualization.VisualizationEngine
save_videos: True

visualizers:
  # Available Visualizers:
  # - Detections: DefaultDetectionVisualizer, FullDetectionVisualizer,
  #               DebugDetectionVisualizer, EllipseDetectionVisualizer
  #               SimpleDetectionStatsVisualizer, DetectionStatsVisualizer
  # - Keypoints: DefaultKeypointsVisualizer, FullKeypointsVisualizer
  # - Images: FrameCountVisualizer
  # - Pitch: PitchVisualizer
  # - Players: PlayerVisualizer, PlayerEllipseVisualizer, CompletePlayerEllipseVisualizer
  frame_counter:
    _target_: tracklab.visualization.FrameCountVisualizer
  pitch:
    _target_: sn_gamestate.visualization.PitchVisualizer
  players:
    _target_: sn_gamestate.visualization.CompletePlayerEllipseVisualizer
  radar:
    _target_: sn_gamestate.visualization.RadarVisualizer

# Color settings for visualization.
colors:
  # Choose the color you want to display:
  # - null: No display.
  # - RGB code: A color in [R, G, B] format.
  # - team: A color based on the assigned team (left or right - can be modified in colors_gs file).
  # - track_id: A color based on the tracking ID (!when id is available).
  default:
    no_id: null  # Color setting for objects with no ID (null means no display).
    prediction: "team"  # Color setting for tracked predictions, based on team.
    ground_truth: null  # Color setting for ground truth, specified as an RGB value.
